type: layout-form
id: root
header:
  - type: header
    title: App Configuration
    logo: icon.webp
form:
  - $include: __resource_group_select_or_create.yaml

  - type: fieldset
    subitems:
      - type: row
        subitems:
          - type: textfield
            name: Name
            produces:
              - variable: app_configuration_name
      - type: row
        subitems:
          - type: combo
            name: Select Region
            items: []
            source:
              cmd: |
                az account list-locations
              path-id: $[*].name
              path-name: $[*].displayName
            produces:
              - variable: app_configuration_region
      - type: 'action-row'
        name: Create App Configuration
        consumes:
          - resource_group_name
          - app_configuration_name
          - app_configuration_region
        verify: |
            az appconfig show --resource-group ${resource_group_name} --name ${app_configuration_name}
        install: az appconfig create --resource-group ${resource_group_name} --name ${app_configuration_name} --location ${app_configuration_region}
        uninstall: az appconfig delete --resource-group ${resource_group_name} --name ${app_configuration_name} --yes

footer:
  - type: footer
    id: footer
    subitems:
      - type: button
        id: install_button
        text: Install
